# Generated by Django 3.0 on 2021-09-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datemvt', models.DateTimeField(db_column='DateMvt')),
                ('refdoc', models.CharField(db_column='RefDoc', max_length=20)),
                ('typemvt', models.CharField(db_column='TypeMvt', max_length=1)),
                ('montant', models.FloatField(db_column='Montant')),
                ('mtlettre', models.TextField(db_column='MtLettre')),
                ('taux', models.FloatField(db_column='Taux')),
                ('devise', models.CharField(db_column='Devise', max_length=10)),
                ('motif', models.CharField(db_column='Motif', max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
