# Generated by Django 3.0 on 2021-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20210917_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droit',
            options={'permissions': (('entree', 'Onglet Entrée'), ('sortie', 'Onglet Sortie'), ('categorie', 'Onglet Référentiel'), ('rapport', 'Onglet Rapport'))},
        ),
        migrations.AddField(
            model_name='location',
            name='compte',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
