# Generated by Django 3.0 on 2021-09-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='mtlettre',
        ),
        migrations.AddField(
            model_name='caisse',
            name='departement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='operation.Departement'),
            preserve_default=False,
        ),
    ]
