# Generated by Django 3.0 on 2021-09-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_taux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='refdoc',
            field=models.CharField(db_column='RefDoc', max_length=100),
        ),
    ]
