# Generated by Django 3.0 on 2021-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_societe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droit',
            options={'permissions': (('entree', 'Onglet Entrée'), ('sortie', 'Onglet Sortie'), ('categorie', 'Onglet Référentiel'), ('rapport', 'Onglet Rapport'), ('exportation', 'Onglet Exportation'))},
        ),
        migrations.AddField(
            model_name='caisse',
            name='operation',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
