# Generated by Django 3.0 on 2021-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20211007_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='operation',
            field=models.CharField(blank=True, choices=[('S', 'Sortie'), ('E', 'Entrée')], max_length=1, null=True),
        ),
    ]
