# Generated by Django 3.0 on 2021-10-16 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0012_auto_20211015_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droit',
            options={'permissions': (('entree', 'Onglet Entrée'), ('entreemodi', 'Onglet Modifier Entrée'), ('entreesup', 'Onglet Supprimer Entrée'), ('sortiemodi', 'Onglet Modifier Sortie'), ('sortiesup', 'Onglet Supprimer Sortie'), ('superviseur', 'Etat Besoins Superviseur'), ('regularisa', 'Onglet Régularisation'), ('soldephysi', 'Onglet Solde Physique'), ('sortie', 'Onglet Sortie'), ('categorie', 'Onglet Référentiel'), ('rapport', 'Onglet Rapport'), ('exportation', 'Onglet Exportation'))},
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datemvt', models.DateTimeField(db_column='DateMvt')),
                ('montant', models.FloatField(db_column='Montant')),
                ('devise', models.CharField(db_column='Devise', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
