# Generated by Django 3.0 on 2021-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20211016_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solde',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='solde',
            name='montant',
        ),
        migrations.AddField(
            model_name='solde',
            name='devisecdf',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solde',
            name='devisecfa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solde',
            name='deviseeuro',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solde',
            name='deviseusd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
