# Generated by Django 3.0 on 2021-10-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_auto_20211016_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superviseur',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superviseurdata', to='operation.Departement'),
        ),
    ]
