# Generated by Django 3.0 on 2021-10-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_auto_20211018_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatBesoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datemvt', models.DateField()),
                ('demandeur', models.CharField(max_length=100)),
                ('motif', models.TextField()),
                ('devise', models.CharField(max_length=10)),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.Superviseur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailEtatBesoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prix', models.FloatField()),
                ('qte', models.FloatField()),
                ('etatbesoin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.EtatBesoin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
