# Generated by Django 3.0 on 2021-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_detailetatbesoin_etatbesoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailetatbesoin',
            name='item',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
