# Generated by Django 3.0 on 2021-10-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_detailetatbesoin_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
