# Generated by Django 3.0 on 2021-10-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0019_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatbesoin',
            name='etat',
            field=models.CharField(choices=[('N', 'Normal'), ('C', 'Caisse'), ('A', 'Admin')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='solde',
            name='datemvt',
            field=models.DateTimeField(db_column='DateMvt', unique=True),
        ),
    ]
