# Generated by Django 3.0 on 2021-10-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_caisse_demandeurboss'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatBesoinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagebs', models.TextField()),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.Caisse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
