# Generated by Django 3.0 on 2021-10-29 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0026_auto_20211029_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='userAdmi',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='userSup',
        ),
        migrations.AddField(
            model_name='etatbesoin',
            name='userAdmi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adminuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
