# Generated by Django 3.0 on 2021-10-30 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0029_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='delai',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signature',
            name='txt',
            field=models.TextField(verbose_name='Mot de passe'),
        ),
    ]
