# Generated by Django 3.0 on 2021-10-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_auto_20211030_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
