# Generated by Django 3.0 on 2021-10-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0031_signature_etat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droit',
            options={'permissions': (('entree', 'Onglet Entrée'), ('entreeajout', 'Onglet Ajout Entrée'), ('entreemodi', 'Onglet Modifier Entrée'), ('entreesup', 'Onglet Supprimer Entrée'), ('sortieajout', 'Onglet Ajout Sortie'), ('sortiemodi', 'Onglet Modifier Sortie'), ('sortiesup', 'Onglet Supprimer Sortie'), ('superviseur', 'Etat Besoins Superviseur'), ('validation', 'Validation Etat Besoins'), ('regularisa', 'Onglet Régularisation'), ('soldephysi', 'Onglet Solde Physique'), ('sortie', 'Onglet Sortie'), ('categorie', 'Onglet Référentiel'), ('rapport', 'Onglet Rapport'), ('exportation', 'Onglet Exportation'), ('signature', 'Onglet Signature'), ('etatbesoin', 'Etat Besoins'))},
        ),
        migrations.AlterField(
            model_name='etatbesoin',
            name='etat',
            field=models.CharField(choices=[('R', 'Rejet'), ('N', 'Normal'), ('C', 'Caisse'), ('A', 'Admin'), ('V', 'Verificateur')], default='N', max_length=1),
        ),
    ]
