# Generated by Django 3.0 on 2021-11-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0034_auto_20211031_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureEtatBesoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prix', models.FloatField()),
                ('datemvt', models.DateTimeField(db_column='DateMvt')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('etatbesoin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.EtatBesoin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
