# Generated by Django 3.0 on 2021-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0035_factureetatbesoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureetatbesoin',
            name='facture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
