# Generated by Django 3.0 on 2021-11-18 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0036_factureetatbesoin_facture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'verbose_name': 'Cle de validation', 'verbose_name_plural': 'Cle de validation'},
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imageuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
