# Generated by Django 3.0 on 2021-11-27 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0037_auto_20211118_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='id',
        ),
        migrations.AlterField(
            model_name='affectation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectation',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='operation.Zone'),
            preserve_default=False,
        ),
    ]
