# Generated by Django 3.0 on 2021-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0038_auto_20211127_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='libelle',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
