# Generated by Django 3.0 on 2021-11-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0041_auto_20211128_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloture',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='operation.Zone'),
            preserve_default=False,
        ),
    ]
