# Generated by Django 3.0 on 2021-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0043_auto_20211128_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloture',
            name='datemvt',
            field=models.DateField(db_column='DateMvt'),
        ),
    ]
