# Generated by Django 3.0 on 2021-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0044_auto_20211128_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloture',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
