# Generated by Django 3.0 on 2021-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0046_solde_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heure', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
