# Generated by Django 3.2.2 on 2022-01-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0048_auto_20211228_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droit',
            options={'permissions': (('entree', 'Onglet Entrée'), ('entreeajout', 'Onglet Ajout Entrée'), ('entreemodi', 'Onglet Modifier Entrée'), ('entreesup', 'Onglet Supprimer Entrée'), ('sortieajout', 'Onglet Ajout Sortie'), ('sortiemodi', 'Onglet Modifier Sortie'), ('sortiesup', 'Onglet Supprimer Sortie'), ('superviseur', 'Etat Besoins Superviseur'), ('validation', 'Validation Etat Besoins'), ('regularisa', 'Onglet Régularisation'), ('soldephysi', 'Onglet Solde Physique'), ('soldephysiajout', 'Onglet Ajout Solde Physique'), ('soldephysimodi', 'Onglet Modifier Solde Physique'), ('soldephysisup', 'Onglet Supprimer Solde Physique'), ('sortie', 'Onglet Sortie'), ('categorie', 'Onglet Référentiel'), ('rapport', 'Onglet Rapport'), ('exportation', 'Onglet Exportation'), ('signature', 'Onglet Signature'), ('etatbesoin', 'Etat Besoins'), ('dashboard', 'Dashboard'), ('caissep', 'Voir Rapport toute Caisse'))},
        ),
    ]
