# Generated by Django 3.2.2 on 2022-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_four', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('email_four', models.CharField(max_length=50)),
                ('telfour', models.CharField(max_length=20, unique=True)),
                ('fax_four', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pays', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_banque', models.CharField(max_length=60)),
            ],
        ),
    ]
