# Generated by Django 3.2.2 on 2022-01-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_typ_decl', models.CharField(max_length=10)),
                ('s_typ_decl', models.CharField(max_length=4)),
                ('num_valid', models.CharField(max_length=25, unique=True)),
                ('poste', models.CharField(max_length=50)),
                ('montantdecl', models.FloatField()),
                ('mode_paie', models.CharField(max_length=20)),
                ('contact_ben', models.CharField(max_length=20)),
                ('monnaie', models.CharField(max_length=10)),
                ('mode_trans', models.CharField(max_length=20)),
                ('num_fac', models.CharField(max_length=15)),
                ('date_fac', models.DateField()),
                ('date_valid', models.DateField()),
                ('banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.tbl_banque')),
                ('cod_pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.pays')),
                ('name_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.fournisseur')),
            ],
        ),
    ]
