# Generated by Django 3.2.2 on 2022-01-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiedeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepaie', models.DateField(auto_now_add=True)),
                ('montpaie', models.FloatField()),
                ('id_declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne_declarate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif', models.CharField(max_length=20, unique=True)),
                ('designation', models.TextField()),
                ('qtefour', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('prix', models.FloatField()),
                ('id_declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Element_conx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(max_length=20)),
                ('mont_elem', models.FloatField()),
                ('id_declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.declaration')),
            ],
        ),
    ]
