# Generated by Django 3.2.2 on 2022-01-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0003_element_conx_ligne_declarate_paiedeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='element_conx',
            name='num_valid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ligne_declarate',
            name='num_valid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
