# Generated by Django 3.2.2 on 2022-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0004_auto_20220112_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='montpay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
