# Generated by Django 3.2.2 on 2022-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0006_paiedeclaration_numfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mvt_rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numlicence', models.CharField(blank=True, max_length=25, null=True)),
                ('codep', models.CharField(blank=True, max_length=40, null=True)),
                ('report', models.FloatField(default=0)),
                ('montantlice', models.FloatField(default=0)),
                ('montantp', models.FloatField(default=0)),
                ('monnaie', models.CharField(blank=True, max_length=5, null=True)),
                ('datvalid', models.DateField()),
            ],
        ),
    ]
