# Generated by Django 3.0.14 on 2022-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0009_auto_20220124_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='datop',
            field=models.DateField(blank=True, null=True),
        ),
        
    ]
