# Generated by Django 3.0.14 on 2022-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0010_auto_20220414_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='code_typ_decl',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='contact_ben',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_fac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_valid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='mode_trans',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='monnaie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='num_fac',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='poste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='s_typ_decl',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
